# Generated by Django 3.1.3 on 2020-11-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Qabul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
                ('master_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('date_visit', models.DateField()),
                ('time_visit', models.TimeField()),
                ('message', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
