# Generated by Django 3.1.3 on 2020-11-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qabul',
            old_name='date_visit',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='qabul',
            old_name='master_name',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='qabul',
            old_name='service_name',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='qabul',
            old_name='time_visit',
            new_name='time',
        ),
    ]
