# Generated by Django 3.1.3 on 2020-11-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201130_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Komputer',
        ),
    ]
