# Generated by Django 3.1.3 on 2020-12-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_komputer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qabul',
            new_name='Mijozlar_New',
        ),
    ]
