# Generated by Django 3.1.3 on 2020-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201201_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
