# Generated by Django 3.1.3 on 2020-12-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201202_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aloqa_New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
