# Generated by Django 3.1.3 on 2020-12-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201202_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aloqa_new',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
